[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#e8630a"
backgroundColor = "#0e1117"  
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"

[client]
toolbarMode = "minimal"